bunch of changes

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,13 +3,13 @@
 
 currentBranch="$(git rev-parse --abbrev-ref HEAD)"
 
-if [ "$currentBranch" = "main" ]; then
-  echo "You can't commit directly to main branch"
-  exit 1
-fi
+# if [ "$currentBranch" = "main" ]; then
+#   echo "You can't commit directly to main branch"
+#   exit 1
+# fi
 
 # docker run -u node --rm -v $PWD/.npmrc:/home/node/app/.npmrc -v $PWD/:/home/node/app -w /home/node/app node:18.15 sh -c '[ ! -d ./node_modules ] && npm install ; npm run lint'
 
 # pnpm
-pnpm run lint-staged
+# pnpm run lint-staged
 # pnpx lint-staged
